sudo: required

language: ruby

services:
  - docker

# whitelist
branches:
  only:
    - master

before_install:
  - docker build -t murphylab/cellorganizer .

script:
  - docker images 
  - docker run -d murphylab/cellorganizer /bin/sh -c "cd cellorganizer/demos/2D/demo2D00/ && bash ./demo2D00.sh"
