sudo: required

language: ruby

services:
  - docker

# whitelist
branches:
  only:
    - master

before_install:
  - docker build -t murphylab/cellorganizer .

script:
  - docker images
  - docker run -td murphylab/cellorganizer 
  - export CONTAINERID=$(docker ps | awk '{ print $1,$2 }' | grep murphylab/cellorganizer | awk '{print $1}')
  - docker exec $CONTAINERID ./cellorganizer/demos/2D/demo2D01/demo2D01.sh
  - docker exec $CONTAINERID ./cellorganizer/demos/2D/demo2D02/demo2D02.sh
  - docker exec $CONTAINERID ./cellorganizer/demos/2D/demo2D04/demo2D04.sh
  - docker exec $CONTAINERID ./cellorganizer/demos/2D/demo2D05/demo2D05.sh
  - docker exec $CONTAINERID ./cellorganizer/demos/2D/demo2D06/demo2D06.sh
  - docker exec $CONTAINERID ./cellorganizer/demos/3D/demo3D11/demo3D11.sh
  - docker exec $CONTAINERID ./cellorganizer/demos/3D/demo3D12/demo3D12.sh
  - docker stop $CONTAINERID
