sudo: required

language: ruby

services:
  - docker

# whitelist
branches:
  only:
    - master

before_install:
  - docker build -t murphylab/cellorganizer .

script:
  - docker images
  - docker run -td murphylab/cellorganizer 
  - export ID=$(docker ps | awk '{ print $1,$2 }' | grep murphylab/cellorganizer | awk '{print $1}')
  - docker exec --user murphylab $ID sh -c "cd ./cellorganizer/demos/2D/demo2D00/ && bash demo2D00.sh"
  - docker exec --user murphylab $ID sh -c "cd ./cellorganizer/demos/2D/demo2D01/ && bash demo2D01.sh"
  - docker exec --user murphylab $ID sh -c "cd ./cellorganizer/demos/2D/demo2D02/ && bash demo2D02.sh"
  - docker exec --user murphylab $ID sh -c "cd ./cellorganizer/demos/2D/demo2D04/ && bash demo2D04.sh"
  - docker exec --user murphylab $ID sh -c "cd ./cellorganizer/demos/2D/demo2D05/ && bash demo2D05.sh"
