sudo: required

language: ruby

services:
  - docker

# whitelist
branches:
  only:
    - master

before_install:
  - docker build -t murphylab/cellorganizer .

script:
  - docker images
  - docker run -td murphylab/cellorganizer 
  - export ID=$(docker ps | awk '{ print $1,$2 }' | grep murphylab/cellorganizer | awk '{print $1}')
  - docker exec $ID ./cellorganizer/demos/2D/demo2D01/demo2D01.sh
  - docker exec $ID ./cellorganizer/demos/2D/demo2D00/demo2D00.sh
